---
name: module3_task2
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Run script to setup Hugo
        run: |
          cd module3_task2/
          ./setup.sh
        shell: bash

      - name: Build and create package
        run: |
          cd module3_task2/
          make lint

      - name: Run tests
        run: |
          cd module3_task2/
          make build
          make validate
          make integration-tests
          make unit-tests
          make clean

      - name: Archiving package
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task2/awesome-website.zip
